# Generated by Django 5.0.3 on 2024-04-02 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_paper_assigned_paper_reviewer1_paper_reviewer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
