# Generated by Django 5.0.3 on 2024-04-02 02:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_paper_paper_id_alter_paper_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paper_id',
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
