# Generated by Django 5.0.3 on 2024-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_paper_paper_id_alter_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='review1_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='review2_status',
            field=models.BooleanField(default=False),
        ),
    ]
